hydra:
  job:
    name: ${backbone.name}_${backbone.topk}
  run:
    dir: /Users/gen/workspace/long-context-experiments/bug_localization/output/${hydra:job.name}${run_suffix}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  _target_: src.baselines.backbones.bm25.bm25_retriever.BM25Backbone
  name: bm25-retriever
  data_path: ${data_source.repos_dir}
  topk: 0
  percent: 100 # retrieve the max so we can derive smaller percentages
  k1: 0.9
  b: 0.4
  useDependencyGraph: False

data_source:
  _target_: src.baselines.data_sources.hf_data_source.HFDataSource
  repos_dir: /Users/gen/workspace/longCodeArena/cloned_repos_test 
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test

reindex: False
run_suffix: "_100_percent"